### PR TITLE
Refactor covalent radii, bonding rules, and overlap detection

### LINKED ISSUE #38: adjust covalent radii
current bonding rules based on cordero covalent radii miss ionic/dative bonds in MOFs, esp. w/ heavy atoms (Ba, I) and metals (Cu, Zn)

- [x] adjust values
- [x] explain adjustment in docs
- [x] don't set `missing` for missing values, just omit them
- [x] coords and box are optional co-kwargs for `make_bonds!` (fix the function signature)
- [x] move logic for detection of bond boundary-crossing to `is_bonded`

### PR DESCRIPTION
**Pull request by eahenle**
- refactored covalent radii
- refactored bonding rules
- added better overlap checking function
- updated .travis.yml for Julia 1.6.0

Covalent radii are now easier to work with.  Augmented Cordero values w/ Manz data.  `get_covalent_radii()` returns Dict w/ all radii in Angstroms (no more standard deviations); `get_covalent_radii(sym)` returns radius of single element.

Bonding rules are easier to work with.  Removed minimum distance (was never used for anything).  Bonding rule set can be calculated from default covalent radii w/ `bondingrules()` or from customized covalent radii dictionary w/ `bondingrules(covalent_radii=dictionary)`

Overlap detection on a crystal applies simple rule from covalent radii.  `overlap(crystal, apply_pbc)` compares atoms' pairwise distances to the lesser of the pairs' covalent radii.  Could do better still, but it's an improvement over applying a user-supplied tolerance to every pair of coordinates.

Closes #38
Partially addresses #42 but should be augmented further

### CODE REVIEW

**Comment by SimonEnsemble** [comment]
much improved bonding rules!
#### comments
* if you can do function overloading, this is clear than making a single function that takes in multiple types (a `Union`). faster too maybe? don't know, but I find it more clear.
* defined some intermediate vars to make clearer what the function was doing, took me a min to understand
#### questions
* I think the `overlap` doc string is now not pertinent to the `Crystal` input--- since it doesn't use `tol`, but rather the bonding rules.
* `overlap` computes the distance between two atoms. then it asks if the distance is less than the minimum of the two radii of the atoms involved. but shouldn't it be considered overlap if `r < cr_i + cr_j`? think of two atoms as spheres right against each other. I suspect this will give a lot of errors if you don't build in a tolerance, but I could be wrong. see our PR on the overlap for inspiration, don't want to give up on that PR, but I feel like this PR is making that one obsolete since that's what we were trying to do there anyway-- use the bonding rules.

**Comment by eahenle** [comment]
>     * if you can do function overloading, this is clear than making a single function that takes in multiple types (a `Union`). faster too maybe? don't know, but I find it more clear.

Yes, more clear.  Also should be faster, since the individual functions are now branch-less (`if` is slow)
 

>     * defined some intermediate vars to make clearer what the function was doing, took me a min to understand

Also more clear, but possibly slower, due to garbage collection on the intermediate variables


>     * I think the `overlap` doc string is now not pertinent to the `Crystal` input--- since it doesn't use `tol`, but rather the bonding rules.

There are two signatures for `overlap` now: one for `Coords` and one for `Crystal`.  I wasn't sure about removing the ability to set an absolute tolerance, so I left the original one--meant to ask about this.  I can get rid of the old one, or we can have both options; either way, I will fix up the docstring.


>     * `overlap` computes the distance between two atoms. then it asks if the distance is less than the minimum of the two radii of the atoms involved. but shouldn't it be considered overlap if `r < cr_i + cr_j`?

`r == cr_i + cr_j` is the criterion for the longest bond between `i` and `j`.  `r < cr_i + cr_j` doesn't always mean `i` and `j` are *too* close, just that the bond length is less than maximum.  The centers of `i` and `j` being within each other's covalent radii, however, will tend to mean they are genuinely too close.  For example, we give carbon a covalent radius of 0.88 and hydrogen 0.38, meaning we will infer a bond if C and H are separated by no more than 1.26 Å, which is actually fairly permissive.  The average C-H bond length is around 1.1 Å.  No C-H bond will ever be as short as 0.38 Å, so that was a safe choice for asserting an overlap.  It would probably be safe to say that 0.88 Å is too short, so maybe the overlap threshold should be the max of the two radii.

**Comment by SimonEnsemble** [comment]
> due to garbage collection on the intermediate variables
not sure how smart the compiler is. might be faster b/c now u aren't slicing an array and constructing another array at an intermediate step. hard to know since the compiler is so opaque to me! probably small difference anyway.

>  I wasn't sure about removing the ability to set an absolute tolerance, so I left the original one
agree it's good to keep original just in case.
I think u should modify the `overlap` function to handle atoms named as e.g. `C23`, like we did here:
https://github.com/SimonEnsemble/Xtals.jl/pull/62/files
then, every time a crystal is constructed, you call this overlap function without worrying about `C23` breaking it. 

then in the `check_overlap` function we can call your new function using the radii! I think this will be a more rigorous overlap test. I think users should be aware when there is overlap in their crystals, since then the fidelity of the sim is in question. 
https://github.com/SimonEnsemble/Xtals.jl/blob/master/src/crystal.jl#L453
this will make our old PR [here](https://github.com/SimonEnsemble/Xtals.jl/pull/62) obsolete, I think. and the reason we pursued that is for a more rigorous check of overlap when the xtal is built.

I SEE, thanks for explaining. I guess checking for overlap is not an exact science, and I'm not sure there is a rigorous number we can use to check for it. `< min(r_i, r_j)` seems it will have a lot of false okay's to me, but I don't know of a better solution, and this is ten times better than not accounting for the van der waals radii! so I'm super happy with this rule. and it's better than tripping false not okay's all the time, since a slightly too-short bond will not impact adsorption simulations too much.

**Comment by eahenle** [comment]
@SimonEnsemble changes made, ready to merge

**Comment by SimonEnsemble** [comment]
awesome. just one more thing:
* I think this doesn't properly check overlap when you add two crystals? I suspect you want to assert that the overlap flag is `false`. https://github.com/SimonEnsemble/Xtals.jl/blob/refactor_covalent_radii/src/crystal.jl#L1130-L1132

**Comment by eahenle** [comment]
> assert that the overlap flag is `false`

Added non-overlap assertion to default `+(::Crystal,::Crystal)` and updated unit test

*Now* it's ready to merge :grin:

**Pull request closed without merging**
